export const SELLER_PRODUCTS_REQUEST = "SELLER_PRODUCTS_REQUEST";
export const SELLER_PRODUCTS_SUCCESS = "SELLER_PRODUCTS_SUCCESS";
export const SELLER_PRODUCTS_FAIL = "SELLER_PRODUCTS_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST_BY_SELLER = "NEW_PRODUCT_REQUEST_BY_SELLER";
export const NEW_PRODUCT_SUCCESS_BY_SELLER = "NEW_PRODUCT_SUCCESS_BY_SELLER";
export const NEW_PRODUCT_RESET_BY_SELLER = "NEW_PRODUCT_RESET_BY_SELLER";
export const NEW_PRODUCT_FAIL_BY_SELLER = "NEW_PRODUCT_FAIL_BY_SELLER";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST_BY_SELLER =
  "UPDATE_PRODUCT_REQUEST_BY_SELLER";
export const UPDATE_PRODUCT_SUCCESS_BY_SELLER =
  "UPDATE_PRODUCT_SUCCESS_BY_SELLER";
export const UPDATE_PRODUCT_RESET_BY_SELLER = "UPDATE_PRODUCT_RESET_BY_SELLER";
export const UPDATE_PRODUCT_FAIL_BY_SELLER = "UPDATE_PRODUCT_FAIL_BY_SELLER";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST_BY_SELLER =
  "DELETE_PRODUCT_REQUEST_BY_SELLER";
export const DELETE_PRODUCT_SUCCESS_BY_SELLER =
  "DELETE_PRODUCT_SUCCESS_BY_SELLER";
export const DELETE_PRODUCT_RESET_BY_SELLER = "DELETE_PRODUCT_RESET_BY_SELLER";
export const DELETE_PRODUCT_FAIL_BY_SELLER = "DELETE_PRODUCT_FAIL_BY_SELLER";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_DETAILS_REQUEST_BY_SELLER =
  "PRODUCT_DETAILS_REQUEST_BY_SELLER";
export const PRODUCT_DETAILS_SUCCESS_BY_SELLER =
  "PRODUCT_DETAILS_SUCCESS_BY_SELLER";
export const PRODUCT_DETAILS_FAIL_BY_SELLER = "PRODUCT_DETAILS_FAIL_BY_SELLER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
